export const words = [
  {
    word: "serendipity",
    definition: "Unexpected good fortune discovered by chance.",
    example: "Finding the perfect picnic spot felt like pure serendipity.",
    etymology: "Coined in 1754 from the tale 'The Three Princes of Serendip'.",
    pronunciation: "seh-ren-DIP-ih-tee",
  },
  {
    word: "luminous",
    definition: "Full of or shedding light; bright or shining.",
    example: "Her ideas were as luminous as the stars over the campsite.",
    pronunciation: "LOO-mih-nus",
  },
  {
    word: "wanderlust",
    definition: "A strong desire to travel and explore the world.",
    example: "He booked a last-minute train because wanderlust won again.",
    pronunciation: "WAHN-der-lust",
  },
  {
    word: "ephemeral",
    definition: "Lasting for a very short time.",
    example: "The pink sunrise was beautiful and ephemeral.",
    pronunciation: "eh-FEM-er-ul",
  },
  {
    word: "ember",
    definition: "A small, glowing piece of coal or wood in a dying fire.",
    example: "We watched an ember pulse while the night grew quiet.",
    pronunciation: "EM-ber",
  },
  {
    word: "quench",
    definition: "To satisfy thirst or to put out a fire.",
    example: "A cold lemonade was enough to quench the hike's heat.",
    pronunciation: "kwench",
  },
  {
    word: "glimmer",
    definition: "A faint or wavering light; a small sign of hope.",
    example: "There was a glimmer of kindness in every note she left.",
    pronunciation: "GLIM-er",
  },
  {
    word: "tether",
    definition: "A rope or chain used to tie something; to connect closely.",
    example: "We tethered the balloon so it would not drift away.",
    pronunciation: "TEH-ther",
  },
  {
    word: "sprout",
    definition: "To begin to grow; a new shoot of a plant.",
    example: "Ideas began to sprout once the team started sketching.",
    pronunciation: "SPROWT",
  },
  {
    word: "whimsy",
    definition: "Playfully quaint or fanciful behavior or humor.",
    example: "The cafe was full of whimsy, from mismatched mugs to chalk doodles.",
    pronunciation: "WIM-zee",
  },
  {
    word: "glean",
    definition: "To collect bit by bit from various sources.",
    example: "She could glean a whole story from a few quick texts.",
    pronunciation: "gleen",
  },
  {
    word: "hatch",
    definition: "To emerge from an egg; to devise a plan.",
    example: "They met at dawn to hatch a simple birthday surprise.",
    pronunciation: "hatch",
  },
  {
    word: "zest",
    definition: "Great enthusiasm and energy; the outer peel of a citrus fruit.",
    example: "He tackled the new recipe with unexpected zest.",
    pronunciation: "zest",
  },
  {
    word: "hush",
    definition: "To make or become silent.",
    example: "A hush fell over the crowd before the lights flicked on.",
    pronunciation: "hush",
  },
  {
    word: "kindle",
    definition: "To light or set on fire; to inspire emotion.",
    example: "The story managed to kindle everyone's curiosity.",
    pronunciation: "KIN-dul",
  },
  {
    word: "ripple",
    definition: "A small wave on the surface of water; a spreading effect.",
    example: "Her laugh sent a ripple of joy through the room.",
    pronunciation: "RIP-ul",
  },
  {
    word: "crisp",
    definition: "Firm, dry, and brittle; pleasingly neat and clear.",
    example: "The autumn air felt crisp and inviting.",
    pronunciation: "krisp",
  },
  {
    word: "mosaic",
    definition: "A pattern produced by arranging small pieces together.",
    example: "Their stories created a mosaic of shared memories.",
    pronunciation: "moh-ZAY-ik",
  },
  {
    word: "snug",
    definition: "Comfortable, warm, and cozy; fitting closely.",
    example: "We found a snug corner to escape the wind.",
    pronunciation: "snug",
  },
  {
    word: "brisk",
    definition: "Quick and active; sharp or abrupt.",
    example: "A brisk walk cleared his head before the call.",
    pronunciation: "brisk",
  },
  {
    word: "glade",
    definition: "An open space in a forest.",
    example: "They picnicked in a quiet glade beside the stream.",
    pronunciation: "glayd",
  },
  {
    word: "bustle",
    definition: "Energetic activity and movement.",
    example: "The kitchen was all bustle as dinner came together.",
    pronunciation: "BUS-ul",
  },
  {
    word: "spark",
    definition: "A small fiery particle; a trigger for action.",
    example: "That compliment was the spark she needed to apply.",
    pronunciation: "spark",
  },
  {
    word: "meander",
    definition: "To follow a winding course; to wander without purpose.",
    example: "We let the conversation meander late into the night.",
    pronunciation: "mee-AN-der",
  },
  {
    word: "savor",
    definition: "To enjoy something completely, especially taste or smell.",
    example: "Take a moment to savor the quiet before the day begins.",
    pronunciation: "SAY-ver",
  },
  {
    word: "gleam",
    definition: "A bright or steady light; to shine softly.",
    example: "A gleam of excitement flashed in her eyes.",
    pronunciation: "gleem",
  },
  {
    word: "soothe",
    definition: "To gently calm or relieve.",
    example: "Warm tea can soothe even the busiest afternoon.",
    pronunciation: "sooth",
  },
  {
    word: "sprightly",
    definition: "Lively and full of energy.",
    example: "His sprightly dance moves surprised everyone at the party.",
    pronunciation: "SPRYT-lee",
  },
  {
    word: "dusk",
    definition: "The time just after sunset; twilight.",
    example: "We raced the tide and reached shore at dusk.",
    pronunciation: "dusk",
  },
  {
    word: "meadow",
    definition: "A field of grass and wildflowers.",
    example: "They rolled out a blanket in the sunlit meadow.",
    pronunciation: "MED-oh",
  },
  {
    word: "flicker",
    definition: "To burn or shine with an unsteady light; a brief feeling.",
    example: "A flicker of doubt crossed his face before he agreed.",
    pronunciation: "FLIK-er",
  },
  {
    word: "nudge",
    definition: "A gentle push or encouragement.",
    example: "Sometimes a small nudge is enough to start a big habit.",
    pronunciation: "nuj",
  },
  {
    word: "frolic",
    definition: "To play and move about cheerfully and energetically.",
    example: "The dogs love to frolic in the fresh snow.",
    pronunciation: "FRAH-lik",
  },
  {
    word: "anchor",
    definition: "A heavy object to keep a vessel in place; a reliable support.",
    example: "Her morning routine was the anchor for calmer days.",
    pronunciation: "ANG-ker",
  },
  {
    word: "bloom",
    definition: "To produce flowers; to flourish or thrive.",
    example: "New friendships can bloom faster than expected.",
    pronunciation: "bloom",
  },
  {
    word: "shimmer",
    definition: "To shine with a soft, wavering light.",
    example: "The lake began to shimmer as the sun climbed higher.",
    pronunciation: "SHIM-er",
  },
  {
    word: "lull",
    definition: "To calm or send to sleep with soothing sounds; a temporary pause.",
    example: "A lull in the chatter let the music shine through.",
    pronunciation: "lull",
  },
  {
    word: "cocoon",
    definition: "A protective covering; a space to develop quietly.",
    example: "She treated the weekend as a cocoon for new ideas.",
    pronunciation: "kuh-KOON",
  },
  {
    word: "drift",
    definition: "To be carried along by currents of air or water; to move aimlessly.",
    example: "Let your mind drift and see what surfaces.",
    pronunciation: "drift",
  },
  {
    word: "twirl",
    definition: "To spin quickly and lightly.",
    example: "He gave the umbrella a playful twirl in the rain.",
    pronunciation: "twurl",
  },
  {
    word: "venture",
    definition: "A risky or daring journey; to dare to do something.",
    example: "She decided to venture outside her comfort zone tonight.",
    pronunciation: "VEN-chur",
  },
  {
    word: "sprinkle",
    definition: "To scatter small drops or particles over something.",
    example: "Sprinkle a little joy into your Monday routine.",
    pronunciation: "SPRIN-kul",
  },
  {
    word: "breeze",
    definition: "A gentle wind; something easy to accomplish.",
    example: "With friends beside us, the climb felt like a breeze.",
    pronunciation: "breez",
  },
  {
    word: "harbor",
    definition: "A sheltered place for ships; to keep a thought or feeling.",
    example: "They built a plan to harbor everyone from the rainstorm.",
    pronunciation: "HAR-ber",
  },
  {
    word: "cheer",
    definition: "A shout of encouragement; a feeling of happiness.",
    example: "One text from her was enough to cheer the whole team.",
    pronunciation: "cheer",
  },
  {
    word: "soar",
    definition: "To fly or rise high; to increase rapidly.",
    example: "Confidence can soar after one genuine compliment.",
    pronunciation: "soar",
  },
  {
    word: "hum",
    definition: "A low, steady continuous sound; to be busy and active.",
    example: "The studio began to hum with focused energy.",
    pronunciation: "hum",
  },
  {
    word: "trail",
    definition: "A path or track; to draw or be dragged along.",
    example: "We followed the lanterns that lit the trail home.",
    pronunciation: "trayl",
  },
  {
    word: "glisten",
    definition: "To shine with a sparkling light.",
    example: "Raindrops on the window began to glisten under the lamp.",
    pronunciation: "GLIS-en",
  },
  {
    word: "amble",
    definition: "To walk or move at a slow, relaxed pace.",
    example: "After dinner we amble through the neighborhood to unwind.",
    pronunciation: "AM-bul",
  },
];
