export const words = [
  {
    word: "boobs",
    definition: "An informal term referring to the breasts, particularly those of a woman.",
    example: "The essay’s tone faltered when it resorted to juvenile references to boobs.",
    etymology: "Slang from the early 20th century, likely derived from 'booby,' meaning something foolish or playful.",
  },
  {
    word: "aporia",
    definition: "A state of unresolved doubt or logical impasse reached through reasoning.",
    example: "The argument ends deliberately in aporia rather than resolution.",
    etymology: "From Greek *aporia*, meaning 'difficulty' or 'impasse.'",
  },
  {
    word: "logorrhea",
    definition: "Excessive or uncontrolled talkativeness, often at the expense of coherence.",
    example: "The paper’s central idea was buried beneath pages of logorrhea.",
    etymology: "From Greek *logos* ('word') and *rhein* ('to flow').",
  },
  {
    word: "susurrus",
    definition: "A soft, murmuring or whispering sound.",
    example: "The susurrus of conversation filled the lecture hall before the speaker began.",
    etymology: "From Latin *susurrus*, meaning 'whisper or murmur.'",
  },
  {
    word: "equivocal",
    definition: "Open to more than one interpretation; deliberately ambiguous.",
    example: "His equivocal response avoided committing to a position.",
    etymology: "From Latin *aequivocus*, meaning 'of equal voice.'",
  },
  {
    word: "inchoate",
    definition: "Only partly formed or developed; not yet clear.",
    example: "She articulated an inchoate but promising theory.",
    etymology: "From Latin *inchoare*, meaning 'to begin.'",
  },
  {
    word: "recondite",
    definition: "Little known or difficult to understand; obscure but precise.",
    example: "The book explores recondite aspects of moral philosophy.",
    etymology: "From Latin *reconditus*, meaning 'hidden away.'",
  },
  {
    word: "discursive",
    definition: "Digressive or wide-ranging in speech or writing.",
    example: "The essay is engaging but overly discursive.",
    etymology: "From Latin *discursus*, meaning 'to run about.'",
  },
  {
    word: "desultory",
    definition: "Lacking a clear plan or direction; jumping from one thing to another.",
    example: "Their discussion was desultory, touching briefly on many topics.",
    etymology: "From Latin *desultorius*, meaning 'leaping about.'",
  },
  {
    word: "provisional",
    definition: "Arranged or accepted temporarily, pending further confirmation.",
    example: "We reached a provisional agreement subject to revision.",
    etymology: "From Latin *provisio*, meaning 'foresight.'",
  },
  {
    word: "attenuated",
    definition: "Weakened or reduced in force, effect, or value.",
    example: "Over time, the original meaning became attenuated.",
    etymology: "From Latin *attenuare*, meaning 'to make thin.'",
  },
  {
    word: "exigency",
    definition: "An urgent need or pressing situation.",
    example: "The exigencies of the moment forced a decision.",
    etymology: "From Latin *exigere*, meaning 'to demand.'",
  },
  {
    word: "anachronistic",
    definition: "Belonging to a different time period than the one depicted.",
    example: "The character’s views feel anachronistic in a modern setting.",
    etymology: "From Greek *ana-* ('against') and *chronos* ('time').",
  },
  {
    word: "tacit",
    definition: "Understood or implied without being stated.",
    example: "There was tacit agreement not to revisit the issue.",
    etymology: "From Latin *tacitus*, meaning 'silent.'",
  },
  {
    word: "ostensible",
    definition: "Appearing or claimed to be one thing, possibly misleading.",
    example: "The ostensible purpose concealed a different motive.",
    etymology: "From Latin *ostendere*, meaning 'to show.'",
  },
  {
    word: "obdurate",
    definition: "Stubbornly refusing to change one’s opinion or course of action.",
    example: "He remained obdurate despite mounting evidence.",
    etymology: "From Latin *obdurare*, meaning 'to harden.'",
  },
  {
    word: "contingent",
    definition: "Dependent on certain conditions or events.",
    example: "Funding is contingent on committee approval.",
    etymology: "From Latin *contingere*, meaning 'to touch upon.'",
  },
  {
    word: "immanent",
    definition: "Existing or operating within something rather than externally imposed.",
    example: "The critique focuses on immanent contradictions within the theory.",
    etymology: "From Latin *immanere*, meaning 'to remain within.'",
  },
  {
    word: "salubrious",
    definition: "Health-giving or beneficial.",
    example: "A more salubrious work schedule improved morale.",
    etymology: "From Latin *salubris*, meaning 'healthful.'",
  },
  {
    word: "intransigent",
    definition: "Unwilling to compromise or change.",
    example: "Negotiations stalled due to intransigent positions on both sides.",
    etymology: "From Latin *intransigens*, meaning 'uncompromising.'",
  },
  {
    word: "specious",
    definition: "Superficially plausible but actually incorrect or misleading.",
    example: "The argument is persuasive but ultimately specious.",
    etymology: "From Latin *speciosus*, meaning 'attractive or showy.'",
  },
  {
    word: "prolix",
    definition: "Excessively long and tedious in speech or writing.",
    example: "The report was thorough but prolix.",
    etymology: "From Latin *prolixus*, meaning 'extended.'",
  },
  {
    word: "expository",
    definition: "Intended to explain or clarify.",
    example: "The opening chapter is largely expository.",
    etymology: "From Latin *exponere*, meaning 'to set forth.'",
  },
  {
    word: "equanimity",
    definition: "Mental calmness and composure, especially in difficult situations.",
    example: "She handled the criticism with remarkable equanimity.",
    etymology: "From Latin *aequanimitas*, meaning 'evenness of mind.'",
  },
];
